### ISSUE TITLE
ERROR: failed to download out of all possible locations

### ISSUE THREAD

**Issue by Parth6288** [lnarayanan68/ELK-Heat-Template#2]
Hi I am getting subjected error while running the below command:

> /usr/share/elasticsearch/bin/plugin install mobz/elasticsearch-head

Error :
**-> Installing mobz/elasticsearch-head...
Trying https://github.com/mobz/elasticsearch-head/archive/master.zip ...
ERROR: failed to download out of all possible locations..., use --verbose to get detailed information**

**Comment by lnarayanan68** [comment]
Works fine for me.. Please see the below output

-> Installing mobz/elasticsearch-head...
Trying https://github.com/mobz/elasticsearch-head/archive/master.zip ...
Downloading .........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................DONE
Verifying https://github.com/mobz/elasticsearch-head/archive/master.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
Installed head into /usr/share/elasticsearch/plugins/head



If you are using a proxy 

/usr/share/elasticsearch/bin/plugin install -DproxyPort=80 -DproxyHost=www.example.com mobz/elasticsearch-head
